name: Test and Analyze with Triggers and SonarCloud
description: Run node tests based on triggers, optional SonarCloud
branding:
  icon: check-square
  color: blue

inputs:
  ### Required
  commands:
    description: Commands to run tests, start with '|' for multi-line
    required: true

  dir:
    description: App/package directory
    required: true

  node_version:
    description: Node version to use (e.g., '22')
    required: true

  ### Typical / recommended
  cache:
    description: Package manager for caching; e.g. npm, yarn, pnpm
    default: npm

  sonar_args:
    # https://docs.sonarcloud.io/advanced-setup/analysis-parameters/
    description: SonarCloud command line arguments
    default: |
      -Dsonar.organization=bcgov-sonarcloud
      -Dsonar.projectKey=bcgov_${{ github.repository }}

  sonar_token:
    description: Sonar token, provide unpopulated token for pre-setup (will skip)

  triggers:
    description: Paths (array) used to trigger a build; e.g. ('./backend/' './frontend/)

  supply_scan:
    description: Enable supply chain attack detection using @aikidosec/safe-chain (opt-in)
    default: "false"

  dep_scan:
    description: "Enable dependency and export analysis using Knip for JS/TS projects. Options: off (skip), warn (run but don't fail), error (run and fail on issues)"
    default: "warn"

  knip_config:
    description: "Path to custom Knip configuration file (relative to workspace root). If not provided, uses action's default configuration"
    default: ""

  ### Usually a bad idea / not recommended
  diff_branch:
    description: Branch to diff against
    default: ${{ github.event.repository.default_branch }}

  repository:
    description: Non-default repository to clone (used for testing this action)
    default: ${{ github.repository }}

  branch:
    description: Non-default branch to clone (used for testing this action)
    default: ""

outputs:
  triggered:
    description: Whether the action was triggered based on path changes
    value: ${{ steps.diff.outputs.triggered }}

runs:
  using: composite
  steps:
    - name: Warnings for breaking changes
      shell: bash
      run: |
        # Warnings for breaking changes
        if [ ! -z "${{ inputs.sonar_project_token }}" ]; then
          echo -e "\n⚠️  Breaking change: sonar_project_token renamed"
          echo -e "\n\tAction: rename sonar_project_token to sonar_token\n"
          exit 1
        fi

        if [ ! -z "${{ inputs.sonar_comment_token }}" ]; then
          echo -e "\n⚠️  Breaking change: sonar_comment_token deprecated"
          echo -e "\n\tAction: remove sonar_comment_token parameter\n"
          exit 1
        fi

    # Send triggers to diff action, but only for pull requests
    - id: diff
      uses: bcgov/action-diff-triggers@0d193029efd26c76aeacaa84aba3328de8198370 # v0.2.0
      with:
        triggers: ${{ github.event_name == 'pull_request' && inputs.triggers || '' }}
        diff_branch: ${{ inputs.diff_branch }}

    # If triggered and (dep or supply) enabled: prepare tools first
    # Checkout action repository for dependencies
    - name: Checkout action repository for dependencies
      if: steps.diff.outputs.triggered == 'true' && ((inputs.supply_scan != 'false') || inputs.dep_scan != 'off')
      uses: actions/checkout@v6
      with:
        repository: bcgov/action-test-and-analyse

    # Setup node version (for tool installation, no cache yet - file doesn't exist)
    - uses: actions/setup-node@v6
      if: steps.diff.outputs.triggered == 'true'
      with:
        node-version: ${{ inputs.node_version }}

    - if: steps.diff.outputs.triggered == 'true' && ((inputs.supply_scan != 'false') || inputs.dep_scan != 'off')
      shell: bash
      run: |
        # Setup safe-chain and/or knip
        set -e

        # Install and initialize safe-chain
        if [ "${{ inputs.supply_scan }}" != "false" ]; then
          SAFE_CHAIN_VERSION=$(jq -er '.dependencies["@aikidosec/safe-chain"]' package.json)
          npm install -g "@aikidosec/safe-chain@$SAFE_CHAIN_VERSION"
          safe-chain setup-ci
        fi

        # Install knip and copy default configuration to temporary directory
        if [ "${{ inputs.dep_scan }}" != "off" ]; then
          KNIP_VERSION=$(jq -er '.dependencies["knip"]' package.json)
          npm install -g "knip@$KNIP_VERSION"
          cp .knip.json "${{ runner.temp }}/.knip.json"
        fi

    # Checkout the target repository - SonarCloud requires a full clone
    - uses: actions/checkout@v6
      if: steps.diff.outputs.triggered == 'true'
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.branch }}
        fetch-depth: 0

    # Setup node with caching (now that package-lock.json exists)
    - uses: actions/setup-node@v6
      if: steps.diff.outputs.triggered == 'true'
      with:
        node-version: ${{ inputs.node_version }}
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.dir }}/package-lock.json

    # Run tests, hopefully generating coverage for SonarCloud
    - if: steps.diff.outputs.triggered == 'true'
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: ${{ inputs.commands }}

    ### Optional SonarCloud

    # If sonar_token
    - if: inputs.sonar_token && steps.diff.outputs.triggered == 'true'
      uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9 # v7.0.0
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
      with:
        projectBaseDir: ${{ inputs.dir }}
        args: >
          ${{ inputs.sonar_args }}

    # If triggered and (dep or supply) enabled: run analysis tools
    - if: steps.diff.outputs.triggered == 'true' && inputs.dep_scan != 'off'
      shell: bash
      run: |
        # Run Knip for dependency and export analysis
        set -e
        cd "${{ github.workspace }}/${{ inputs.dir }}"

        # Set config file (suppress hints when using default config)
        if [ -n "${{ inputs.knip_config }}" ]; then
          KNIP_CONFIG="--config=${{ github.workspace }}/${{ inputs.knip_config }}"
        else
          KNIP_CONFIG="--config=${{ runner.temp }}/.knip.json --no-config-hints"
        fi

        # Run knip with JSON output for annotations (stderr separate to avoid corrupting JSON)
        set +e
        knip --dependencies --exports --reporter json ${KNIP_CONFIG} > knip-output.json 2> knip-error.log
        KNIP_EXIT_CODE=$?
        set -e

        # Validate JSON before parsing (in case of non-JSON errors)
        if [ "$KNIP_EXIT_CODE" -ne 0 ] && [ -f knip-output.json ]; then
          if ! jq empty knip-output.json >/dev/null 2>&1; then
            echo "::error::Knip failed with exit code $KNIP_EXIT_CODE and did not produce valid JSON"
            if [ -f knip-error.log ]; then
              cat knip-error.log
            fi
            exit $KNIP_EXIT_CODE
          fi
        fi

        # Parse JSON and create annotations
        if [ -f knip-output.json ] && [ -s knip-output.json ] && jq empty knip-output.json >/dev/null 2>&1; then
          # Count issues
          UNUSED_FILES=$(jq -r '.files | length // 0' knip-output.json 2>/dev/null || echo "0")
          
          # Count dependencies and exports across all issues
          UNUSED_DEPS=$(jq -r '[.issues[].dependencies[]?] | length' knip-output.json 2>/dev/null || echo "0")
          UNUSED_DEV_DEPS=$(jq -r '[.issues[].devDependencies[]?] | length' knip-output.json 2>/dev/null || echo "0")
          UNUSED_EXPORTS=$(jq -r '[.issues[].exports[]?] | length' knip-output.json 2>/dev/null || echo "0")
          
          if [ "$UNUSED_FILES" != "0" ] || [ "$UNUSED_DEPS" != "0" ] || [ "$UNUSED_DEV_DEPS" != "0" ] || [ "$UNUSED_EXPORTS" != "0" ]; then
            
            # Create annotations for unused files
            if [ "$UNUSED_FILES" != "0" ]; then
              jq -r '.files[]? | "::warning file=\(.),line=1::Unused file: \(.)"' knip-output.json 2>/dev/null || true
            fi
            # Create annotations for unused dependencies
            jq -r '.issues[]? | select(.dependencies != null and (.dependencies | length) > 0) | . as $issue | $issue.dependencies[]? | "::warning file=\($issue.file // "package.json"),line=\(.line // 1)::Unused dependency: \(.name)"' knip-output.json 2>/dev/null || true
            
            # Create annotations for unused devDependencies
            jq -r '.issues[]? | select(.devDependencies != null and (.devDependencies | length) > 0) | . as $issue | $issue.devDependencies[]? | "::warning file=\($issue.file // "package.json"),line=\(.line // 1)::Unused devDependency: \(.name)"' knip-output.json 2>/dev/null || true
            
            # Create annotations for unused exports
            jq -r '.issues[]? | select(.exports != null and (.exports | length) > 0) | . as $issue | $issue.exports[]? | "::notice file=\($issue.file // "unknown"),line=\(.line // 1)::Unused export: \(.name)"' knip-output.json 2>/dev/null || true
          fi
          
          # Run knip with default output for detailed summary (with hints)
          # Build config without --no-config-hints for summary
          if [ -n "${{ inputs.knip_config }}" ]; then
            SUMMARY_CONFIG="--config=${{ github.workspace }}/${{ inputs.knip_config }}"
          else
            SUMMARY_CONFIG="--config=${{ runner.temp }}/.knip.json"
          fi
          
          # Capture detailed output for summary
          set +e
          knip --dependencies --exports ${SUMMARY_CONFIG} > knip-summary.txt 2>&1
          set -e
          # Add summary to step summary
          {
            echo "## 🔍 Knip Analysis Results"
            echo ""
            echo ""
            echo "### Detailed Output"
            echo "```"
            if [ -f knip-summary.txt ]; then
              cat knip-summary.txt
            fi
            echo "```"
            echo "| Category | Count |"
            echo "|----------|-------|"
            echo "| Unused files | $UNUSED_FILES |"
            echo "| Unused dependencies | $UNUSED_DEPS |"
            echo "| Unused devDependencies | $UNUSED_DEV_DEPS |"
            echo "| Unused exports | $UNUSED_EXPORTS |"
            echo ""
            if [ $KNIP_EXIT_CODE -ne 0 ]; then
              echo "⚠️ **Issues found** - See annotations above for details"
            else
              echo "✅ **No issues found**"
            fi
          } >> "$GITHUB_STEP_SUMMARY"
        fi

        # Handle result
        if [ $KNIP_EXIT_CODE -eq 0 ]; then
          echo "✅ Knip analysis complete - no unused dependencies or exports found"
        else
          echo "⚠️  Knip found issues"
          if [ "${{ inputs.dep_scan }}" = "warn" ]; then
            echo "Running in warn mode - workflow will continue"
            exit 0
          else
            echo "Running in error mode - workflow will exit"
            exit $KNIP_EXIT_CODE
          fi
        fi

    # Fix - Clone for action.yml and other verifications
    - name: Checkout Action repo to pass tests
      if: always() && inputs.repository != github.repository
      uses: actions/checkout@v6
