name: Test and Analyze with Triggers and SonarCloud
description: Run node tests based on triggers, optional SonarCloud
branding:
  icon: check-square
  color: blue

inputs:
  ### Required
  commands:
    description: Commands to run tests, start with '|' for multi-line
    required: true

  dir:
    description: App/package directory
    required: true
    pattern: "^[a-zA-Z0-9._/-]+$"

  node_version:
    description: Node version to use (e.g., '18', '20', '22')
    required: true
    pattern: '^[0-9]+(\.[0-9]+)*$'

  ### Typical / recommended
  cache:
    description: Package manager for caching; e.g. npm, yarn, pnpm
    default: npm
    pattern: "^(npm|yarn|pnpm)$"

  sonar_args:
    # https://docs.sonarcloud.io/advanced-setup/analysis-parameters/
    description: SonarCloud command line arguments
    default: |
      -Dsonar.organization=bcgov-sonarcloud
      -Dsonar.projectKey=bcgov_${{ github.repository }}

  sonar_token:
    description: Sonar token, provide unpopulated token for pre-setup (will skip)
    pattern: "^[a-zA-Z0-9]{20,}$"

  triggers:
    description: Paths (array) used to trigger a build; e.g. ('./backend/' './frontend/)

  supply_scan:
    description: Enable supply chain attack detection using @aikidosec/safe-chain (opt-in)
    default: "false"
    pattern: "^(true|false)$"

  lockfile_verify:
    description: Enable lockfile verification to ensure lockfile is up to date with package.json
    default: "true"
    pattern: "^(true|false)$"

  ### Usually a bad idea / not recommended
  diff_branch:
    description: Branch to diff against
    default: ${{ github.event.repository.default_branch }}
    pattern: "^[a-zA-Z0-9._/-]+$"

  repository:
    description: Non-default repository to clone (used for testing this action)
    default: ${{ github.repository }}
    pattern: "^[a-zA-Z0-9-_]+/[a-zA-Z0-9-_]+$"

  branch:
    description: Non-default branch to clone (used for testing this action)
    default: ""
    pattern: "^[a-zA-Z0-9._/-]*$"

outputs:
  triggered:
    description: Whether the action was triggered based on path changes
    value: ${{ steps.diff.outputs.triggered }}

runs:
  using: composite
  steps:
    - name: Warnings for breaking changes
      shell: bash
      run: |
        # Warnings for breaking changes
        if [ ! -z "${{ inputs.sonar_project_token }}" ]; then
          echo -e "\n⚠️  Breaking change: sonar_project_token renamed"
          echo -e "\n\tAction: rename sonar_project_token to sonar_token\n"
          exit 1
        fi

        if [ ! -z "${{ inputs.sonar_comment_token }}" ]; then
          echo -e "\n⚠️  Breaking change: sonar_comment_token deprecated"
          echo -e "\n\tAction: remove sonar_comment_token parameter\n"
          exit 1
        fi

    # Send triggers to diff action, but only for pull requests
    - id: diff
      uses: bcgov/action-diff-triggers@0d193029efd26c76aeacaa84aba3328de8198370 # v0.2.0
      with:
        triggers: ${{ github.event_name == 'pull_request' && inputs.triggers || '' }}
        diff_branch: ${{ inputs.diff_branch }}

    # Shallow clone is faster, but SonarCloud requires a full clone
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.branch }}

    # Setup node and cache dir
    - uses: actions/setup-node@v6
      if: steps.diff.outputs.triggered == 'true'
      with:
        node-version: ${{ inputs.node_version }}
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.dir }}/package-lock.json

    # Setup supply chain attack detection (opt-in)
    - name: Set up supply chain attack detection
      if: steps.diff.outputs.triggered == 'true' && inputs.supply_scan == 'true'
      shell: bash
      run: |
        set -e
        echo "🔒 Installing @aikidosec/safe-chain for supply chain attack detection..."
        if ! npm install -g @aikidosec/safe-chain@1.1.10; then
          echo "❌ Failed to install @aikidosec/safe-chain"
          exit 1
        fi
        if ! safe-chain setup-ci; then
          echo "❌ Failed to setup safe-chain"
          exit 1
        fi
        echo "✅ Safe-chain setup complete"

    # Run tests, hopefully generating coverage for SonarCloud
    - if: steps.diff.outputs.triggered == 'true'
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: ${{ inputs.commands }}

    ### Optional SonarCloud

    # If sonar_token
    - if: inputs.sonar_token && steps.diff.outputs.triggered == 'true'
      uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
      with:
        projectBaseDir: ${{ inputs.dir }}
        args: >
          ${{ inputs.sonar_args }}

    # Fix - Clone for action.yml and other verifications
    - name: Checkout Action repo to pass tests
      if: always() && inputs.repository != github.repository
      uses: actions/checkout@v6

    # Verify lockfile is up to date with package.json
    - name: Verify lockfile is up to date
      if: always() && steps.diff.outputs.triggered == 'true' && inputs.lockfile_verify == 'true'
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        set -e
        
        # Check if package.json exists
        if [ ! -f "package.json" ]; then
          echo "⚠️  No package.json found, skipping lockfile verification"
          exit 0
        fi
        
        # Detect package manager by checking for lockfiles
        LOCKFILE=""
        PM=""
        
        if [ -f "package-lock.json" ]; then
          LOCKFILE="package-lock.json"
          PM="npm"
        elif [ -f "yarn.lock" ]; then
          LOCKFILE="yarn.lock"
          PM="yarn"
        elif [ -f "pnpm-lock.yaml" ]; then
          LOCKFILE="pnpm-lock.yaml"
          PM="pnpm"
        fi
        
        # Skip if no lockfile found
        if [ -z "$LOCKFILE" ]; then
          echo "ℹ️  No lockfile found, skipping lockfile verification"
          exit 0
        fi
        
        echo "🔍 Verifying $LOCKFILE is up to date with package.json..."
        
        # Update lockfile without installing packages, with error handling
        case "$PM" in
          npm)
            if ! npm install --package-lock-only; then
              echo "❌ Failed to update lockfile with npm"
              exit 1
            fi
            ;;
          yarn)
            # Yarn v2+ (Berry) uses --mode, v1 (Classic) doesn't support it
            if yarn --version 2>/dev/null | grep -q "^1\."; then
              # Yarn v1 doesn't have a lockfile-only option, so we run install
              # This will update yarn.lock if package.json changed
              if ! yarn install; then
                echo "❌ Failed to update lockfile with yarn v1"
                exit 1
              fi
            else
              if ! yarn install --mode update-lockfile; then
                echo "❌ Failed to update lockfile with yarn"
                exit 1
              fi
            fi
            ;;
          pnpm)
            if ! pnpm install --lockfile-only; then
              echo "❌ Failed to update lockfile with pnpm"
              exit 1
            fi
            ;;
        esac
        
        # Check if lockfile changed
        if ! git diff --exit-code "$LOCKFILE" > /dev/null 2>&1; then
          # Restore lockfile before exiting
          git checkout -- "$LOCKFILE"
          echo "❌ Lockfile is out of date with package.json"
          echo "   Please run '$PM install' and commit the updated lockfile"
          exit 1
        fi
        
        echo "✅ Lockfile is up to date"
