name: Test and Analyze with Triggers and SonarCloud
description: Run node tests based on triggers, optional SonarCloud
branding:
  icon: check-square
  color: blue

inputs:
  ### Required
  commands:
    description: Commands to run tests, start with '|' for multi-line
    required: true

  dir:
    description: App/package directory
    required: true
    pattern: "^[a-zA-Z0-9._/-]+$"

  node_version:
    description: Node version to use (e.g., '22')
    required: true
    pattern: '^[0-9]+(\.[0-9]+)*$'

  ### Typical / recommended
  cache:
    description: Package manager for caching; e.g. npm, yarn, pnpm
    default: npm
    pattern: "^(npm|yarn|pnpm)$"

  sonar_args:
    # https://docs.sonarcloud.io/advanced-setup/analysis-parameters/
    description: SonarCloud command line arguments
    default: |
      -Dsonar.organization=bcgov-sonarcloud
      -Dsonar.projectKey=bcgov_${{ github.repository }}

  sonar_token:
    description: Sonar token, provide unpopulated token for pre-setup (will skip)
    pattern: "^[a-zA-Z0-9]{20,}$"

  triggers:
    description: Paths (array) used to trigger a build; e.g. ('./backend/' './frontend/)

  supply_scan:
    description: Enable supply chain attack detection using @aikidosec/safe-chain (opt-in)
    default: "false"
    pattern: "^(true|false)$"

  dep_scan:
    description: "Enable dependency and export analysis using Knip for JS/TS projects. Options: off (skip), warn (run but don't fail), error (run and fail on issues)"
    default: "warn"
    pattern: "^(off|warn|error)$"

  knip_config:
    description: "Path to custom Knip configuration file (relative to workspace root). If not provided, uses action's default configuration"
    default: ""
    pattern: "^(?!.*\\.\\.)[a-zA-Z0-9._/-]*$"

  ### Usually a bad idea / not recommended
  diff_branch:
    description: Branch to diff against
    default: ${{ github.event.repository.default_branch }}
    pattern: "^[a-zA-Z0-9._/-]+$"

  repository:
    description: Non-default repository to clone (used for testing this action)
    default: ${{ github.repository }}
    pattern: "^[a-zA-Z0-9-_]+/[a-zA-Z0-9-_]+$"

  branch:
    description: Non-default branch to clone (used for testing this action)
    default: ""
    pattern: "^[a-zA-Z0-9._/-]*$"

outputs:
  triggered:
    description: Whether the action was triggered based on path changes
    value: ${{ steps.diff.outputs.triggered }}

runs:
  using: composite
  steps:
    - name: Warnings for breaking changes
      shell: bash
      run: |
        # Warnings for breaking changes
        if [ ! -z "${{ inputs.sonar_project_token }}" ]; then
          echo -e "\n⚠️  Breaking change: sonar_project_token renamed"
          echo -e "\n\tAction: rename sonar_project_token to sonar_token\n"
          exit 1
        fi

        if [ ! -z "${{ inputs.sonar_comment_token }}" ]; then
          echo -e "\n⚠️  Breaking change: sonar_comment_token deprecated"
          echo -e "\n\tAction: remove sonar_comment_token parameter\n"
          exit 1
        fi

    # Send triggers to diff action, but only for pull requests
    - id: diff
      uses: bcgov/action-diff-triggers@0d193029efd26c76aeacaa84aba3328de8198370 # v0.2.0
      with:
        triggers: ${{ github.event_name == 'pull_request' && inputs.triggers || '' }}
        diff_branch: ${{ inputs.diff_branch }}

    # If triggered and (dep or supply) enabled: prepare tools first
    # Checkout action repository for dependencies
    - name: Checkout action repository for dependencies
      if: steps.diff.outputs.triggered == 'true' && ((inputs.supply_scan == 'true') || inputs.dep_scan != 'off')
      uses: actions/checkout@v6
      with:
        repository: ${{ github.repository }}
        path: action-repo

    # Install packages globally from package.json
    - name: Install packages globally from package.json
      if: steps.diff.outputs.triggered == 'true' && ((inputs.supply_scan == 'true') || inputs.dep_scan != 'off')
      shell: bash
      run: |
        set -e
        cd action-repo

        # Verify package.json exists
        if [ ! -f "package.json" ]; then
          echo "❌ package.json not found in action repository"
          exit 1
        fi

        # Install packages globally from npm registry using versions from package.json
        # npm can handle semver ranges directly, so we pass the version as-is from package.json
        if [ "${{ inputs.supply_scan }}" = "true" ]; then
          SAFE_CHAIN_VERSION=$(jq -r '.dependencies["@aikidosec/safe-chain"] // empty' package.json)
          if [ -z "$SAFE_CHAIN_VERSION" ] || [ "$SAFE_CHAIN_VERSION" = "null" ]; then
            echo "❌ @aikidosec/safe-chain not found in package.json"
            exit 1
          fi
          npm install -g "@aikidosec/safe-chain@$SAFE_CHAIN_VERSION"
        fi

        if [ "${{ inputs.dep_scan }}" != "off" ]; then
          KNIP_VERSION=$(jq -r '.dependencies["knip"] // empty' package.json)
          if [ -z "$KNIP_VERSION" ] || [ "$KNIP_VERSION" = "null" ]; then
            echo "❌ knip not found in package.json"
            exit 1
          fi
          npm install -g "knip@$KNIP_VERSION"
        fi

    # Setup supply chain attack detection (opt-in)
    - name: Set up supply chain attack detection
      if: steps.diff.outputs.triggered == 'true' && inputs.supply_scan == 'true'
      shell: bash
      run: |
        set -e
        safe-chain setup-ci

    # If triggered: checkout downstream repo and run tests
    # Checkout the repository being tested
    # Shallow clone is faster, but SonarCloud requires a full clone (fetch-depth: 0)
    - uses: actions/checkout@v6
      if: steps.diff.outputs.triggered == 'true'
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.branch }}
        fetch-depth: 0

    # Setup node and cache dir
    - uses: actions/setup-node@v6
      if: steps.diff.outputs.triggered == 'true'
      with:
        node-version: ${{ inputs.node_version }}
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.dir }}/package-lock.json

    # Run tests, hopefully generating coverage for SonarCloud
    - if: steps.diff.outputs.triggered == 'true'
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: ${{ inputs.commands }}

    ### Optional SonarCloud

    # If sonar_token
    - if: inputs.sonar_token && steps.diff.outputs.triggered == 'true'
      uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9 # v7.0.0
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
      with:
        projectBaseDir: ${{ inputs.dir }}
        args: >
          ${{ inputs.sonar_args }}

    # If triggered and (dep or supply) enabled: run analysis tools
    - name: Run Knip for dependency and export analysis
      if: steps.diff.outputs.triggered == 'true' && inputs.dep_scan != 'off'
      shell: bash
      run: |
        set -e
        cd "${{ github.workspace }}/${{ inputs.dir }}"

        # Handle Knip configuration
        KNIP_CONFIG_ARG=""

        if [ -n "${{ inputs.knip_config }}" ]; then
          # User provided a custom config path - validate it exists
          CUSTOM_CONFIG="${{ github.workspace }}/${{ inputs.knip_config }}"
          
          # Ensure resolved path is within workspace
          CUSTOM_CONFIG_ABS=$(realpath "$CUSTOM_CONFIG" 2>/dev/null || echo "")
          WORKSPACE_ABS=$(realpath "${{ github.workspace }}" 2>/dev/null || echo "")
          if [ -z "$CUSTOM_CONFIG_ABS" ] || [ -z "$WORKSPACE_ABS" ]; then
            echo "❌ Invalid knip_config path: unable to resolve absolute path"
            exit 1
          fi
          if [ "${CUSTOM_CONFIG_ABS#$WORKSPACE_ABS}" = "$CUSTOM_CONFIG_ABS" ]; then
            echo "❌ Invalid knip_config path: must be within workspace"
            exit 1
          fi
          
          if [ -f "$CUSTOM_CONFIG" ]; then
            KNIP_CONFIG_ARG="--config=$CUSTOM_CONFIG"
          else
            echo "❌ Custom Knip config not found at $CUSTOM_CONFIG"
            echo "   Please verify the 'knip_config' input path and ensure the file exists."
            exit 1
          fi
        fi

        USING_DEFAULT_CONFIG=false

        if [ -z "$KNIP_CONFIG_ARG" ]; then
          # No custom config provided - use action's default
          # Note: This will overwrite any existing .knip.json in the project directory
          USING_DEFAULT_CONFIG=true
          PROJECT_KNIP=".knip.json"
          
          # Copy default config from the action repository (use absolute path from workspace root)
          DEFAULT_KNIP="${{ github.workspace }}/action-repo/.knip.json"
          if [ ! -f "$DEFAULT_KNIP" ]; then
            echo "❌ Default .knip.json not found in action repository"
            exit 1
          fi
          cp "$DEFAULT_KNIP" "$PROJECT_KNIP"
        fi

        # Suppress configuration hints when using default config (hints are about our upstream config, not user's project)
        # Note: Test workflow uses sed to remove this flag to verify hints work
        KNIP_HINTS_ARG=""
        if [ "$USING_DEFAULT_CONFIG" = "true" ]; then
          KNIP_HINTS_ARG="--no-config-hints"
        fi

        # Run knip and capture exit code (temporarily disable set -e to capture exit code)
        set +e
        knip --dependencies --exports ${KNIP_CONFIG_ARG:+"$KNIP_CONFIG_ARG"} ${KNIP_HINTS_ARG:+"$KNIP_HINTS_ARG"}
        KNIP_EXIT_CODE=$?
        set -e

        if [ $KNIP_EXIT_CODE -ne 0 ]; then
          # If dep_scan is 'warn', don't fail the workflow
          if [ "${{ inputs.dep_scan }}" = "warn" ]; then
            echo "⚠️  Knip found issues but running in warn mode - workflow will continue"
            exit 0
          else
            # dep_scan is 'error' - fail the workflow
            exit $KNIP_EXIT_CODE
          fi
        fi

    # Fix - Clone for action.yml and other verifications
    - name: Checkout Action repo to pass tests
      if: always() && inputs.repository != github.repository
      uses: actions/checkout@v6
