name: Test and Analyze with Triggers and SonarCloud
description: Run node tests based on triggers, optional SonarCloud
branding:
  icon: check-square
  color: blue

inputs:
  ### Required
  commands:
    description: Commands to run tests, start with '|' for multi-line
    required: true

  dir:
    description: App/package directory
    required: true
    pattern: "^[a-zA-Z0-9._/-]+$"

  node_version:
    description: Node version to use (e.g., '18', '20', '22')
    required: true
    pattern: '^[0-9]+(\.[0-9]+)*$'

  ### Typical / recommended
  cache:
    description: Package manager for caching; e.g. npm, yarn, pnpm
    default: npm
    pattern: "^(npm|yarn|pnpm)$"

  sonar_args:
    # https://docs.sonarcloud.io/advanced-setup/analysis-parameters/
    description: SonarCloud command line arguments
    default: |
      -Dsonar.organization=bcgov-sonarcloud
      -Dsonar.projectKey=bcgov_${{ github.repository }}

  sonar_token:
    description: Sonar token, provide unpopulated token for pre-setup (will skip)
    pattern: "^[a-zA-Z0-9]{20,}$"

  triggers:
    description: Paths (array) used to trigger a build; e.g. ('./backend/' './frontend/)

  supply_scan:
    description: Enable supply chain attack detection using @aikidosec/safe-chain (opt-in)
    default: "false"
    pattern: "^(true|false)$"

  dep_scan:
    description: "Enable dependency and export analysis using Knip for JS/TS projects. Options: off/false (skip), warn (run but don't fail), error/true (run and fail on issues)"
    default: "warn"
    pattern: "^(off|false|warn|error|true)$"

  knip_config:
    description: "Path to custom Knip configuration file (relative to workspace root). If not provided, uses action's default configuration"
    default: ""
    pattern: "^(?!.*\\.\\.)[a-zA-Z0-9._/-]*$"

  ### Usually a bad idea / not recommended
  diff_branch:
    description: Branch to diff against
    default: ${{ github.event.repository.default_branch }}
    pattern: "^[a-zA-Z0-9._/-]+$"

  repository:
    description: Non-default repository to clone (used for testing this action)
    default: ${{ github.repository }}
    pattern: "^[a-zA-Z0-9-_]+/[a-zA-Z0-9-_]+$"

  branch:
    description: Non-default branch to clone (used for testing this action)
    default: ""
    pattern: "^[a-zA-Z0-9._/-]*$"

outputs:
  triggered:
    description: Whether the action was triggered based on path changes
    value: ${{ steps.diff.outputs.triggered }}

runs:
  using: composite
  steps:
    - name: Warnings for breaking changes
      shell: bash
      run: |
        # Warnings for breaking changes
        if [ ! -z "${{ inputs.sonar_project_token }}" ]; then
          echo -e "\n⚠️  Breaking change: sonar_project_token renamed"
          echo -e "\n\tAction: rename sonar_project_token to sonar_token\n"
          exit 1
        fi

        if [ ! -z "${{ inputs.sonar_comment_token }}" ]; then
          echo -e "\n⚠️  Breaking change: sonar_comment_token deprecated"
          echo -e "\n\tAction: remove sonar_comment_token parameter\n"
          exit 1
        fi

    # Send triggers to diff action, but only for pull requests
    - id: diff
      uses: bcgov/action-diff-triggers@0d193029efd26c76aeacaa84aba3328de8198370 # v0.2.0
      with:
        triggers: ${{ github.event_name == 'pull_request' && inputs.triggers || '' }}
        diff_branch: ${{ inputs.diff_branch }}

    # Shallow clone is faster, but SonarCloud requires a full clone
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.branch }}

    # Setup node and cache dir
    - uses: actions/setup-node@v6
      if: steps.diff.outputs.triggered == 'true'
      with:
        node-version: ${{ inputs.node_version }}
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.dir }}/package-lock.json

    # Checkout action repository for dependencies (if either tool is needed)
    - name: Checkout action repository for dependencies
      if: steps.diff.outputs.triggered == 'true' && (inputs.supply_scan == 'true' || inputs.dep_scan != 'off' && inputs.dep_scan != 'false')
      uses: actions/checkout@v6
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        path: action-repo

    # Install packages globally from package.json
    - name: Install packages globally from package.json
      if: steps.diff.outputs.triggered == 'true' && (inputs.supply_scan == 'true' || inputs.dep_scan != 'off' && inputs.dep_scan != 'false')
      shell: bash
      run: |
        set -e
        cd action-repo

        # Verify package.json exists
        if [ ! -f "package.json" ]; then
          echo "❌ package.json not found in action repository"
          exit 1
        fi

        # Install packages globally from npm registry using versions from package.json
        echo "🌐 Installing packages globally from package.json..."

        if [ "${{ inputs.supply_scan }}" = "true" ]; then
          SAFE_CHAIN_VERSION=$(jq -r '.dependencies["@aikidosec/safe-chain"]' package.json | sed 's/[\^~]//')
          echo "  Installing @aikidosec/safe-chain@$SAFE_CHAIN_VERSION..."
          if ! npm install -g "@aikidosec/safe-chain@$SAFE_CHAIN_VERSION"; then
            echo "❌ Failed to install @aikidosec/safe-chain globally"
            exit 1
          fi
          echo "  ✓ @aikidosec/safe-chain installed globally"
        fi

        if [ "${{ inputs.dep_scan }}" != "off" ] && [ "${{ inputs.dep_scan }}" != "false" ]; then
          KNIP_VERSION=$(jq -r '.dependencies["knip"]' package.json | sed 's/[\^~]//')
          echo "  Installing knip@$KNIP_VERSION..."
          if ! npm install -g "knip@$KNIP_VERSION"; then
            echo "❌ Failed to install knip globally"
            exit 1
          fi
          echo "  ✓ knip installed globally"
        fi

        echo "✅ Packages installed globally"

    # Setup supply chain attack detection (opt-in)
    - name: Set up supply chain attack detection
      if: steps.diff.outputs.triggered == 'true' && inputs.supply_scan == 'true'
      shell: bash
      run: |
        set -e
        echo "🔒 Setting up @aikidosec/safe-chain..."
        if ! safe-chain setup-ci; then
          echo "❌ Failed to setup safe-chain"
          exit 1
        fi
        echo "✅ Safe-chain setup complete"

    # Run tests, hopefully generating coverage for SonarCloud
    - if: steps.diff.outputs.triggered == 'true'
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: ${{ inputs.commands }}

    - name: Run Knip for dependency and export analysis
      if: steps.diff.outputs.triggered == 'true' && inputs.dep_scan != 'off' && inputs.dep_scan != 'false'
      shell: bash
      run: |
        set -e
        echo "🧹 Running Knip to check for unused dependencies and exports..."
        cd "${{ github.workspace }}/${{ inputs.dir }}" || { echo "❌ Failed to change directory to '${{ github.workspace }}/${{ inputs.dir }}'. Please verify the 'dir' input."; exit 1; }

        # Handle Knip configuration
        KNIP_CONFIG_ARG=""

        if [ -n "${{ inputs.knip_config }}" ]; then
          # User provided a custom config path - validate it exists
          CUSTOM_CONFIG="${{ github.workspace }}/${{ inputs.knip_config }}"
          
          # Ensure resolved path is within workspace
          CUSTOM_CONFIG_ABS=$(realpath "$CUSTOM_CONFIG" 2>/dev/null || echo "")
          WORKSPACE_ABS=$(realpath "${{ github.workspace }}" 2>/dev/null || echo "")
          if [ -z "$CUSTOM_CONFIG_ABS" ] || [ -z "$WORKSPACE_ABS" ]; then
            echo "❌ Invalid knip_config path: unable to resolve absolute path"
            exit 1
          fi
          if [ "${CUSTOM_CONFIG_ABS#$WORKSPACE_ABS}" = "$CUSTOM_CONFIG_ABS" ]; then
            echo "❌ Invalid knip_config path: must be within workspace"
            exit 1
          fi
          
          if [ -f "$CUSTOM_CONFIG" ]; then
            KNIP_CONFIG_ARG="--config=$CUSTOM_CONFIG"
            echo "✅ Using custom Knip config from ${{ inputs.knip_config }}"
          else
            echo "❌ Custom Knip config not found at $CUSTOM_CONFIG"
            echo "   Please verify the 'knip_config' input path and ensure the file exists."
            exit 1
          fi
        fi

        USING_DEFAULT_CONFIG=false

        if [ -z "$KNIP_CONFIG_ARG" ]; then
          # No custom config provided - use action's default
          # Note: This will overwrite any existing .knip.json in the project directory
          echo "ℹ️ Using action's default Knip configuration..."
          USING_DEFAULT_CONFIG=true
          PROJECT_KNIP=".knip.json"
          
          # Try to find the default config from the action
          DEFAULT_KNIP=""
          if [ -f "action-repo/.knip.json" ]; then
            DEFAULT_KNIP="action-repo/.knip.json"
          fi
          
          # If file not found, create default config inline
          if [ -z "$DEFAULT_KNIP" ] || [ ! -f "$DEFAULT_KNIP" ]; then
            echo "📝 Creating default .knip.json with common exceptions..."
            # Use multiline string for better readability and maintainability
            DEFAULT_KNIP_JSON='{
              "ignoreDependencies": [
                "swagger-ui-express",
                "rimraf",
                "@types/node",
                "@types/react",
                "@types/react-dom"
              ],
              "ignoreBinaries": [
                "rimraf"
              ]
            }'
            echo "$DEFAULT_KNIP_JSON" > "$PROJECT_KNIP"
            echo "✅ Applied default .knip.json with common exceptions"
          else
            cp "$DEFAULT_KNIP" "$PROJECT_KNIP"
            echo "✅ Applied default .knip.json with common exceptions"
          fi
        fi

        # Suppress configuration hints when using default config (hints are about our upstream config, not user's project)
        # Note: Test workflow uses sed to remove this flag to verify hints work
        KNIP_HINTS_ARG=""
        if [ "$USING_DEFAULT_CONFIG" = "true" ]; then
          KNIP_HINTS_ARG="--no-config-hints"
        fi

        # Run knip and capture output and exit code (temporarily disable set -e to capture exit code)
        set +e
        KNIP_OUTPUT=$(knip --dependencies --exports ${KNIP_CONFIG_ARG:+"$KNIP_CONFIG_ARG"} ${KNIP_HINTS_ARG:+"$KNIP_HINTS_ARG"} 2>&1)
        KNIP_EXIT_CODE=$?
        set -e
        
        # Strip ANSI color codes and control characters from output
        KNIP_OUTPUT=$(echo "$KNIP_OUTPUT" | sed 's/\x1b\[[0-9;]*m//g' | sed 's/\x1b\[[0-9;]*[a-zA-Z]//g' | sed 's/[\x00-\x1F\x7F]//g')

        # Write Knip output to step summary
        echo "## 🔍 Knip Analysis Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        if [ $KNIP_EXIT_CODE -ne 0 ]; then
          echo "### ⚠️ Issues Found" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Knip found unused dependencies or exports that should be reviewed:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
        else
          echo "### ✅ No Issues Found" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All dependencies and exports are in use." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
        fi

        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "$KNIP_OUTPUT" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        if [ $KNIP_EXIT_CODE -ne 0 ]; then
          echo ""
          echo "⚠️  Knip found unused dependencies or exports"
          echo "ℹ️  Review the output above to clean up your project"
          
          # Add warning annotation to workflow summary (shows in annotations tab)
          echo "::warning::Knip found unused dependencies or exports. Review the detailed output in the step summary."
          
          # Parse output and add individual file-level annotations
          # Track seen issues to avoid duplicates
          declare -A SEEN_ANNOTATIONS
          
          while IFS= read -r line; do
            # Skip empty lines, decorative lines, summary headers, and configuration hints
            if [[ -z "$line" ]] || \
               [[ "$line" =~ ^(Found|✂|─|│|└|├|  |Unused|^$) ]] || \
               [[ "$line" =~ ^(Configuration hints|Unused devDependencies|Unused dependencies|Unused exports|Unresolved imports) ]] || \
               [[ "$line" =~ "Remove from ignoreDependencies" ]] || \
               [[ "$line" =~ "Remove from ignore" ]]; then
              continue
            fi
            
            # Skip lines that are just counts like "(4)" or "(1)"
            if [[ "$line" =~ ^[[:space:]]*\([0-9]+\)[[:space:]]*$ ]]; then
              continue
            fi
            
            # Extract file path with line:column pattern (e.g., "package.json:38:6")
            if [[ "$line" =~ ([^[:space:]]+\.([jt]sx?|json|mjs|cjs)):([0-9]+):([0-9]+) ]]; then
              FILE_PATH="${BASH_REMATCH[1]}"
              LINE_NUM="${BASH_REMATCH[3]}"
              COL_NUM="${BASH_REMATCH[4]}"
              
              # Create unique key for deduplication
              ANNOTATION_KEY="${FILE_PATH}:${LINE_NUM}:${COL_NUM}"
              
              if [[ -z "${SEEN_ANNOTATIONS[$ANNOTATION_KEY]}" ]]; then
                SEEN_ANNOTATIONS[$ANNOTATION_KEY]=1
                
                # Extract clean issue description
                # Remove file path and line/column info, extract just the dependency/export name
                CLEAN_LINE=$(echo "$line" | sed -E "s/.*${FILE_PATH}:[0-9]+:[0-9]+[[:space:]]*//")
                
                # Try to extract just the package/export name (first word after path, or before any description)
                if [[ "$CLEAN_LINE" =~ ^([^[:space:]]+) ]]; then
                  ISSUE_NAME="${BASH_REMATCH[1]}"
                  # Remove any trailing punctuation or description
                  ISSUE_NAME=$(echo "$ISSUE_NAME" | sed 's/[.,;:]$//')
                  echo "::warning file=${FILE_PATH},line=${LINE_NUM},col=${COL_NUM}::Unused: ${ISSUE_NAME}"
                elif [[ -n "$CLEAN_LINE" ]]; then
                  echo "::warning file=${FILE_PATH},line=${LINE_NUM},col=${COL_NUM}::${CLEAN_LINE}"
                else
                  # Fallback: extract package name from the line before the file path
                  if [[ "$line" =~ ([@a-zA-Z0-9_-]+(/[a-zA-Z0-9_-]+)*)[[:space:]]+${FILE_PATH} ]]; then
                    PKG_NAME="${BASH_REMATCH[1]}"
                    echo "::warning file=${FILE_PATH},line=${LINE_NUM},col=${COL_NUM}::Unused: ${PKG_NAME}"
                  fi
                fi
              fi
            # Handle unresolved imports (e.g., "./~bootstrap/scss/bootstrap src/scss/styles.scss:1:17")
            elif [[ "$line" =~ ^([^[:space:]]+)[[:space:]]+([^[:space:]]+\.([jt]sx?|scss|css)):([0-9]+):([0-9]+) ]]; then
              IMPORT_PATH="${BASH_REMATCH[1]}"
              FILE_PATH="${BASH_REMATCH[2]}"
              LINE_NUM="${BASH_REMATCH[4]}"
              COL_NUM="${BASH_REMATCH[5]}"
              
              ANNOTATION_KEY="${FILE_PATH}:${LINE_NUM}:${COL_NUM}:${IMPORT_PATH}"
              
              if [[ -z "${SEEN_ANNOTATIONS[$ANNOTATION_KEY]}" ]]; then
                SEEN_ANNOTATIONS[$ANNOTATION_KEY]=1
                echo "::warning file=${FILE_PATH},line=${LINE_NUM},col=${COL_NUM}::Unresolved import: ${IMPORT_PATH}"
              fi
            fi
          done <<< "$KNIP_OUTPUT"
          
          # If dep_scan is 'warn', don't fail the workflow
          if [ "${{ inputs.dep_scan }}" = "warn" ]; then
            echo "⚠️  Running in warn mode - workflow will continue"
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "> ℹ️ **Warn mode**: Workflow continues despite issues. Consider cleaning up unused dependencies." >> $GITHUB_STEP_SUMMARY
          else
            # dep_scan is 'error' or 'true' - fail the workflow
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "> ❌ **Error mode**: Workflow failed. Please resolve unused dependencies or exports." >> $GITHUB_STEP_SUMMARY
            exit $KNIP_EXIT_CODE
          fi
        else
          echo "✅ Knip analysis complete - no unused dependencies or exports found"
        fi

    ### Optional SonarCloud

    # If sonar_token
    - if: inputs.sonar_token && steps.diff.outputs.triggered == 'true'
      uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9 # v7.0.0
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
      with:
        projectBaseDir: ${{ inputs.dir }}
        args: >
          ${{ inputs.sonar_args }}

    # Fix - Clone for action.yml and other verifications
    - name: Checkout Action repo to pass tests
      if: always() && inputs.repository != github.repository
      uses: actions/checkout@v6
