#!/usr/bin/env node

import * as core from '@actions/core';
import { analyzeKnip } from './knip.js';
import fs from 'node:fs';
import path from 'node:path';

/**
 * Main entry point for the action/CLI.
 */
async function run() {
  try {
    // Inputs from GitHub Actions (or fallback to environment/defaults for CLI)
    const dir = core.getInput('dir') || process.env.KNIP_DIR || '.';
    const knipOutputFile = core.getInput('knip_output') || 'knip-output.json';
    const depScan = core.getInput('dep_scan') || 'warn';
    const knipSummaryFile = 'knip-summary.txt';

    core.info(`Starting analysis in directory: ${dir}`);

    if (!fs.existsSync(knipOutputFile)) {
       core.info(`No Knip output found at ${knipOutputFile}. Skipping analysis.`);
       return;
    }

    const stats = analyzeKnip(knipOutputFile, dir);
    
    // Set outputs for the action
    core.setOutput('unused_files', stats.unusedFiles);
    core.setOutput('unused_deps', stats.unusedDeps);
    core.setOutput('total_issues', stats.totalIssues);

    // Create Step Summary
    if (process.env.GITHUB_STEP_SUMMARY) {
      const summary = core.summary
        .addHeading('🔍 Knip Analysis Results')
        .addTable([
          ['Category', 'Count'],
          ['Unused files', stats.unusedFiles.toString()],
          ['Unused dependencies', stats.unusedDeps.toString()],
          ['Unused devDependencies', stats.unusedDevDeps.toString()],
          ['Unused exports', stats.unusedExports.toString()]
        ]);

      // If a summary text file exists (generated by the raw knip run), include it
      if (fs.existsSync(knipSummaryFile)) {
        const detail = fs.readFileSync(knipSummaryFile, 'utf8');
        summary.addHeading('📋 Full Output', 3)
          .addCodeBlock(detail.replace(/\x1b\[[0-9;]*[a-zA-Z]/g, '')); // Strip ANSI colors
      }

      if (stats.totalIssues > 0) {
        summary.addRaw(`\n⚠️ **Issues found** - See annotations in the Checks tab for details`);
      } else {
        summary.addRaw(`\n✅ **No issues found**`);
      }

      await summary.write();
    } else {
       // CLI Output
       console.log('\n🔍 Knip Analysis Results');
       console.table({
         'Unused files': stats.unusedFiles,
         'Unused dependencies': stats.unusedDeps,
         'Unused devDependencies': stats.unusedDevDeps,
         'Unused exports': stats.unusedExports
       });
    }

    // Handle failure mode
    if (stats.totalIssues > 0) {
      if (depScan === 'error') {
        core.setFailed(`Knip found ${stats.totalIssues} unused items.`);
      } else {
        core.info(`Knip found ${stats.totalIssues} unused items (running in warn mode).`);
      }
    } else {
      core.info('✅ Knip analysis complete - no issues found.');
    }

  } catch (error) {
    core.setFailed(error.message);
  }
}

run();
